<?php
    require_once "../../../../wp-load.php";
?>
// This is a Javascript file generated by PHP for the translations

if ( !window.PhotoCommons ) {
    window.PhotoCommons = {};
}

window.PhotoCommons.translations = {
    "Insert images from Wikimedia Commons" : "<?php _e("Insert images from Wikimedia Commons", "wp-photocommons"); ?>",
    "PhotoCommons" : "<?php _e("PhotoCommons", "wp-photocommons"); ?>"
};
